### ISSUE TITLE
Routing does no respect paths

### ISSUE THREAD

**Issue by darkmattercoder** [marctuscher/osm-fapra#3]
It looks to me as if the route calculation does not take paths into account. Is that correct? Only highway keys are considered. Could we change that?

**Comment by marctuscher** [comment]
This is correct.

You could add „path“ (or any other value for the osm-key „highway“) to the values of motorwayFilter in line 70 (https://github.com/marctuscher/TravellingSalesmanOsm/blob/bfb20e35386f21547ff0501d1add07f2c4e6ce4f/src/graphreader.cpp#L70 ). Just append „path“ to the list of values.

Additionally you may want to add a default speed for path into the speedMap, similar to line 67 (https://github.com/marctuscher/TravellingSalesmanOsm/blob/bfb20e35386f21547ff0501d1add07f2c4e6ce4f/src/graphreader.cpp#L67)

**Comment by darkmattercoder** [comment]
Thanks for pointing me to the right code locations for that.
