### ISSUE TITLE
(docker) Crash on too many nodes

### ISSUE THREAD

**Issue by darkmattercoder** [marctuscher/osm-fapra#4]
I tried your router using your docker image. However, I could not get it to calculate a solution for more than 25 nodes. 

Do you think I would see the same when I build the software by hand? I notice that the calculation only uses one cpu core and my memory gets exhausted. But I am not sure wether this is the reason for the crash.

Any hints how to do further debugging? I aim for a problem with ~55 nodes. And I do not care when it would take a few hours to find a solution. The crash happens after roughly 300 seconds into the calculation for 26 nodes, where a problem with 25 nodes took about 230 seconds to complete.

**Comment by marctuscher** [comment]
I assume you are using the Optimal TSP Solver. 

This solver implements the Held-Karp algorithm in a memory efficient way. However, the space complexity of the Held-Karp algorithm is O (2^n * n) and you likely ran out of memory at more than 25 nodes.Running this algorithmn on a problem with 55 nodes would require approximately 36000 TB of RAM, rendering such a problem practically infeasible.

You should stick to the 2-APX for the 55 node problem, giving you a solution, which path is max. 2 times longer than the optimal path. Note that I'm not sure whether I ever tested the 2-APX on a problem with such many nodes. 

Good explanation of the complexity of Held-Karp:
https://cstheory.stackexchange.com/questions/3581/time-complexity-of-held-karp-algorithm-for-tsp

**Comment by marctuscher** [comment]
Sorry, forgot to answer your question. 

You would very likely see the same when building the software from source. Docker imposes only little overhead compared to running the code natively.
