### ISSUE TITLE
Error loading docker container

### ISSUE THREAD

**Issue by vlaguz** [marctuscher/osm-fapra#5]
I can't load the container successfully.  WHen I run:
docker run -d -v /path/to/datafolder/:/usr/app/data -e FILENAME="yourfilename.osm.pbf" -p 8080:8080 marctuscher/travellingsalesmanosm
I can't connect to localhost:8080:

The container is not running:
~/docker$ sudo docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS                            PORTS               NAMES
32fb9a74da73        marctuscher/travellingsalesmanosm   "/bin/sh -c '/usr/apâ¦"   About a minute ago   Exited (134) About a minute ago                       lucid_montalcini

And logs:
~/docker$ sudo docker logs 32fb9a74da73
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::json_parser::json_parser_error> >'
  what():  <unspecified file>(1): expected value
Aborted (core dumped)

What could it be?

**Comment by marctuscher** [comment]
As stated in the README.md you need to copy a suitable config.json and your .pbf openstreetmap data to the same directory. 

You also need to adjust the path to this data and the filename of the .pbf file in the docker run command.
